POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "Austin Feltan",
    "title": "My Personal Life",
    "url": "123456",
    "likes": 1,
    "userId": "639ce8c57498c8695b9c8e45"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Austin Feltan",
    "title": "My Personal Life",
    "url": "123456",
    "likes": 1,
    "userId": "639ce8c57498c8695b9c8e45"
}