POST http://localhost:3001/api/blogs
Content-Type: application/json

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik55dHN3YSIsImlkIjoiNjM5Y2U4YzU3NDk4Yzg2OTViOWM4ZTQ1IiwiaWF0IjoxNjcxNTUxNzczfQ.dEbmkQzcum4B0OrkbSBN9S16l2BLMYOKajio3cjHHVs

{
    "author": "Austin Feltan",
    "title": "My Personal Life",
    "url": "123456",
    "likes": 1,
    "userId": "639ce8c57498c8695b9c8e45"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Austin Feltan",
    "title": "My Personal Life",
    "url": "123456",
    "likes": 1,
    "userId": "639ce8c57498c8695b9c8e45"
}