POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "Austin Feltan",
    "number": "33450543"
}

### No number
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "Missing"
}

### No name
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "number": "Missing"
}

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "Alternative",
    "number": "2000"
}

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "A",
    "number": "1"
}
